apiVersion: v1
kind: Service
metadata:
  name: azurecontainerpipeline
  namespace: azuremicroservice
spec:
  type: LoadBalancer
  selector:
    app: azurecontainerpipeline
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000